version: '3.8'

services:

  main:
    image: ${LOCAL_DOCKER_IMAGE}

    environment:
        - PROJECT_NAME=${PROJECT_NAME}

    command: sh -c "terminator & bash /home/docky/init.sh"

    volumes:
      - type: bind
        source: ./
        target: /home/docky/pyicub
