services:

  yarpserver:
    image: iitschri/yarp-docker:v3.9.0
    container_name: yarpserver

    command: ["/bin/bash", "-c", "yarpserver --write & sleep 2; yarprun --server /${YARPSRV_NODE:-yarp-node} --log"]

    stdin_open: true
    tty: true
    network_mode: host
    privileged: true
